spring:
  datasource:
    url: jdbc:mariadb://beerfactory.cnoi8wfszlm7.ap-northeast-2.rds.amazonaws.com:3306/beerfactory
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 12341234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
#  key: ${JWT_SECRET_KEY}
  key: 12412421421412alkdjgflasdjflj2j4
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    s3:
      bucket: beertestbucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

