#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    database: H2
#    open-in-view: false
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
spring:
  datasource:
    url: ${{ secrets.DB_URL }}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${{ secrets.DB_NAME }}
    password: ${{ secrets.DB_URL }}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
mail:
  address:
    admin: admin@gmail.com
jwt:
#  key: ${JWT_SECRET_KEY}
  key: ${{ secrets.JWT_SECRET_KEY }}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    s3:
      bucket: ${{ secrets.AWS_BUCKET }}
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.AWS_SECRET_KEY }}