spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: H2
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
mail:
  address:
    admin: admin@gmail.com
jwt:
#  key: ${JWT_SECRET_KEY}
  key: seb40_main_037$654$321$987$456$123$789$321$654$987$456$789$123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    s3:
      bucket: beertestbucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIASL2JGAUHA75BQNE3
      secretKey: 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