spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: H2
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
mail:
  address:
    admin: admin@gmail.com
jwt:
#  key: ${JWT_SECRET_KEY}
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${G3Do0/G1Sy7xs+wAHHzLRKvewCI4HVXiUgPZEawQ}